### ISSUE TITLE
Can't compile a solution on Visual Studio 2019

### ISSUE THREAD

**Issue by wh1t3lord** [root-project/cling#454]
Hello!

I followed these instructions for "building" cling project, but it didn't compile at all.

Instructions:
git clone http://root.cern.ch/git/llvm.git src
cd src
git checkout cling-patches
cd tools
git clone http://root.cern.ch/git/cling.git
git clone http://root.cern.ch/git/clang.git
cd clang
git checkout cling-patches
cd ../..

The VS output of cling project:

1>cling.exp : error LNK2001: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::operator<<<struct std::char_traits<char> >(class std::basic_ostream<char,struct std::char_traits<char> > &,char)" (??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@D@Z)
1>cling.exp : error LNK2001: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::operator<<<struct std::char_traits<char> >(class std::basic_ostream<char,struct std::char_traits<char> > &,char const *)" (??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z)
1>cling.exp : error LNK2001: unresolved external symbol "void * __cdecl operator new(unsigned int)" (??2@YAPAXI@Z)
1>cling.exp : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *)" (??3@YAXPAX@Z)
1>cling.exp : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *,unsigned int)" (??3@YAXPAXI@Z)
1>cling.exp : error LNK2001: unresolved external symbol "public: class std::basic_ostream<char,struct std::char_traits<char> > & __thiscall std::basic_ostream<char,struct std::char_traits<char> >::operator<<(int)" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z)
1>cling.exp : error LNK2001: unresolved external symbol "public: class std::basic_ostream<char,struct std::char_traits<char> > & __thiscall std::basic_ostream<char,struct std::char_traits<char> >::operator<<(float)" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@M@Z)
1>cling.exp : error LNK2001: unresolved external symbol "public: class std::basic_ostream<char,struct std::char_traits<char> > & __thiscall std::basic_ostream<char,struct std::char_traits<char> >::operator<<(double)" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@N@Z)
1>cling.exp : error LNK2001: unresolved external symbol "public: class std::basic_ostream<char,struct std::char_traits<char> > & __thiscall std::basic_ostream<char,struct std::char_traits<char> >::operator<<(class std::basic_ostream<char,struct std::char_traits<char> > & (__cdecl*)(class std::basic_ostream<char,struct std::char_traits<char> > &))" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z)
1>cling.exp : error LNK2001: unresolved external symbol "public: class std::basic_ostream<char,struct std::char_traits<char> > & __thiscall std::basic_ostream<char,struct std::char_traits<char> >::operator<<(void const *)" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@PBX@Z)
1>cling.exp : error LNK2001: unresolved external symbol "void * __cdecl operator new[](unsigned int)" (??_U@YAPAXI@Z)
1>cling.exp : error LNK2001: unresolved external symbol "void __cdecl operator delete[](void *)" (??_V@YAXPAX@Z)
1>cling.exp : error LNK2001: unresolved external symbol "void __cdecl operator delete[](void *,unsigned int)" (??_V@YAXPAXI@Z)
1>cling.exp : error LNK2001: unresolved external symbol "void __cdecl std::_Facet_Register(class std::_Facet_base *)" (?_Facet_Register@std@@YAXPAV_Facet_base@1@@Z)
fatal error LNK1120: 14 unresolved externals

I don't know how to fix it ¯\_(ツ)_/¯

**Comment by mrexodia** [comment]
Running into the exact same issue with Visual Studio 2022. It would be helpful if there was some guide with the 'officially' supported Visual Studio versions.

I followed the instructions [here](https://root-forum.cern.ch/t/compiling-cling-on-windows-msvc-2022/47106/20) and used the Visual Studio generator instead of Ninja as suggested in some other thread:

```
cmake -DCMAKE_INSTALL_PREFIX=./build/install -B build -DCMAKE_BUILD_TYPE=Release -Thost=x64
cmake --build build --config Release
```

http://root.cern.ch/git/llvm.git is c41338c59334340ee4d85a7c9bbdf49a4f59f76b
http://root.cern.ch/git/clang.git is 535acc218f73a05f5602c950898dafda8a45feb7
http://root.cern.ch/git/cling.git is a3805bb26d8bd8284c1278d3d55d265bc2048f2a

All latest as of today...

**Comment by mrexodia** [comment]
Did some digging and it appears the bug was introduced in https://github.com/root-project/cling/commit/e20302182fde9b3964f701efe2ac5a7af140e79a

The fix included a check with `CMAKE_GENERATOR_PLATFORM`, which is not set unless you specify it manually. To fix this I replaced [this line](https://github.com/root-project/cling/blob/a3805bb26d8bd8284c1278d3d55d265bc2048f2a/tools/driver/CMakeLists.txt#L60) with:

```cmake
  if(CMAKE_SIZEOF_VOID_P EQUAL 8)
```

The `CMAKE_SIZEOF_VOID_P` will automatically be set by the `project()` call.

**Comment by bellenot** [comment]
See [Building ROOT from source](https://root.cern/install/build_from_source/). The recommended way is to specify the platform (`-A Win32` or `-A x64`). But I'll check nevertheless

**Comment by mrexodia** [comment]
Yeah that also makes sure Ninja doesn’t work for x64…

**Comment by mrexodia** [comment]
Will also add a few more commits later today. The Cling CMake package is also broken and there is this issue related to _MSC_VER that (apparently) breaks tablegen with VS2022.

**Comment by bellenot** [comment]
There are 19 occurrences of `CMAKE_GENERATOR_PLATFORM` in ROOT. I'll check what can be done

**Comment by mrexodia** [comment]
I somehow managed to open a PR on my own repo, here is a PR to the root project: https://github.com/root-project/root/pull/11632
