### ISSUE TITLE
Missing windows include

### ISSUE THREAD

**Issue by SylvainCorlay** [root-project/cling#352]
I am working on the conda-forge packaging of 0.7, and all seems to work well on Linux and OSX

PR is here: https://github.com/conda-forge/cling-feedstock/pull/39.

On windows, the build is terminating with:

```
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(154): fatal error C1189: #error:  "No Target Architecture"
```

**Comment by SylvainCorlay** [comment]
Fixed in #353.
